language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - libmysqlclient-dev
    - libpq-dev
    - liblua5.3-dev

before_install:
  - >
    case "${TRAVIS_OS_NAME:-linux}" in
    osx)
      brew update --quiet
      brew install mysql
      brew install lua53
      ;;
    esac

script: ./autogen.sh && ./configure --with-mysql --with-pgsql && make
